# Generated by Django 6.0.2 on 2026-03-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back', 'book', 'author'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
